# Generated by Django 3.0.8 on 2020-08-10 03:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employer_id', models.IntegerField(blank=True, null=True)),
                ('company_id', models.IntegerField(blank=True, null=True)),
                ('data_name', models.CharField(blank=True, max_length=255, null=True)),
                ('count', models.IntegerField()),
                ('cleaned', models.IntegerField(blank=True, null=True)),
                ('dated', models.DateTimeField()),
            ],
            options={
                'db_table': 'tbl_vendors',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vendor_id', models.IntegerField(blank=True, null=True)),
                ('email', models.CharField(blank=True, max_length=255, null=True)),
                ('dated', models.DateTimeField()),
            ],
            options={
                'db_table': 'tbl_vendors_data',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='MessageBody',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vendor_id', models.IntegerField(blank=True, null=True)),
                ('email_subject', models.TextField(blank=True, null=True)),
                ('email_body', models.TextField(blank=True, null=True)),
                ('schedule_date', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(default='1', max_length=1)),
                ('employer_id', models.IntegerField(blank=True, null=True)),
                ('company_id', models.IntegerField(blank=True, null=True)),
                ('updated_on', models.DateTimeField()),
            ],
            options={
                'db_table': 'tbl_vendor_schedulers',
                'managed': False,
            },
        ),
    ]
